export const prosCons = [
  {
    id: 1,
    status: "failure",
    title: "Studying without SwiftStudy ❌",
    features: [
      "Overwhelming documents",
      "Manual flashcards",
      "Inefficient study sessions",
      "Hard to memorise traditionally",
      "Time consuming review process",
    ],
  },
  {
    id: 2,
    status: "success",
    title: "Studying with SwiftStudy ✅",
    features: [
      "Instant flashcards",
      "Microlearning boosting memory",
      "Spaced repetition",
      "Efficient study sessions",
      "Fast content reviews",
    ],
  },
];

export const pricingPlans = [
  {
    plan: "Free",
    price: "$0",
    quota: 3,
    features: [
      {
        text: "5 pages per PDF",
        footnote: "The maximum amount of pages per PDF-file.",
      },
      {
        text: "4MB file size limit",
        footnote: "The maximum file size of a single PDF file.",
      },
      {
        text: "Mobile-friendly interface",
      },
      {
        text: "Higher-quality responses",
        footnote: "Better algorithmic responses for enhanced content quality",
        negative: true,
      },
      {
        text: "Priority support",
        negative: true,
      },
    ],
  },
  {
    plan: "Pro",
    price: "$5",
    quota: 50,
    features: [
      {
        text: "25 pages per PDF",
        footnote: "The maximum amount of pages per PDF-file.",
      },
      {
        text: "16MB file size limit",
        footnote: "The maximum file size of a single PDF file.",
      },
      {
        text: "Mobile-friendly interface",
      },
      {
        text: "Higher-quality responses",
        footnote: "Better algorithmic responses for enhanced content quality",
      },
      {
        text: "Priority support",
      },
    ],
  },
];

export const demoFlashcards = [
  {
    _id: "1",
    file: "abcd",
    user: "abcdefghijk",
    question: "What is the capital of France?",
    answer: "Paris",
    status: "Needs revising",
    lastStudied: "2024-07-23T14:00:00Z",
  },
  {
    _id: "2",
    file: "efgh",
    user: "lmnopqrstuv",
    question: "What is the largest planet in our solar system?",
    answer: "Jupiter",
    status: "Revise soon",
    lastStudied: "2024-07-23T13:00:00Z",
  },
  {
    _id: "3",
    file: "ijkl",
    user: "wxyzabcdefg",
    question: "Who wrote 'To Kill a Mockingbird'?",
    answer: "Harper Lee",
    status: "Needs revising",
    lastStudied: "2024-07-23T12:00:00Z",
  },
  {
    _id: "4",
    file: "mnop",
    user: "hijklmnopqr",
    question: "What is the chemical symbol for water?",
    answer: "H2O",
    status: "Needs revising",
    lastStudied: "2024-07-23T11:00:00Z",
  },
  {
    _id: "5",
    file: "qrst",
    user: "stuvwxyzabc",
    question: "What is the capital of Japan?",
    answer: "Tokyo",
    status: "Needs revising",
    lastStudied: "2024-07-23T10:00:00Z",
  },
  {
    _id: "6",
    file: "uvwx",
    user: "defghijklmno",
    question: "Who painted the Mona Lisa?",
    answer: "Leonardo da Vinci",
    status: "Needs revising",
    lastStudied: "2024-07-23T09:00:00Z",
  },
  {
    _id: "7",
    file: "yzab",
    user: "pqrstuvwxyz",
    question: "What is the speed of light?",
    answer: "299,792,458 meters per second",
    status: "Needs revising",
    lastStudied: "2024-07-23T08:00:00Z",
  },
  {
    _id: "8",
    file: "cdef",
    user: "abcdefgijkl",
    question: "What is the tallest mountain in the world?",
    answer: "Mount Everest",
    status: "Needs revising",
    lastStudied: "2024-07-23T07:00:00Z",
  },
  {
    _id: "9",
    file: "ghij",
    user: "mnopqrstuvwx",
    question: "Who is known as the 'Father of Computers'?",
    answer: "Charles Babbage",
    status: "Revise soon",
    lastStudied: "2024-07-23T06:00:00Z",
  },
  {
    _id: "10",
    file: "klmn",
    user: "yznopqrstuvw",
    question: "What is the capital of Canada?",
    answer: "Ottawa",
    status: "Needs revising",
    lastStudied: "2024-07-23T05:00:00Z",
  },
  {
    _id: "11",
    file: "opqr",
    user: "abcdefghijkl",
    question: "What is the powerhouse of the cell?",
    answer: "Mitochondria",
    status: "Needs revising",
    lastStudied: "2024-07-23T04:00:00Z",
  },
  {
    _id: "12",
    file: "stuv",
    user: "mnopqrstuvwx",
    question: "Who discovered penicillin?",
    answer: "Alexander Fleming",
    status: "Needs revising",
    lastStudied: "2024-07-23T03:00:00Z",
  },
  {
    _id: "13",
    file: "wxyz",
    user: "yzabcdefghijkl",
    question: "What is the largest ocean on Earth?",
    answer: "Pacific Ocean",
    status: "Mastered",
    lastStudied: "2024-07-23T02:00:00Z",
  },
  {
    _id: "14",
    file: "abcd",
    user: "mnopqrstuvwx",
    question: "What is the hardest natural substance on Earth?",
    answer: "Diamond",
    status: "Needs revising",
    lastStudied: "2024-07-23T01:00:00Z",
  },
  {
    _id: "15",
    file: "efgh",
    user: "abcdefghijklm",
    question: "What is the smallest unit of life?",
    answer: "Cell",
    status: "Needs revising",
    lastStudied: "2024-07-23T00:00:00Z",
  },
];
